### PR TITLE
Replace type synonyms at List

### PR DESCRIPTION
**Pull request by gspia**
That is, change the Elem, Lookup and Zip functions. This commit also adds a sentence to README.mk.

Ok, looks like that I can make PR from branch to the master and this initialized the pr msg with the commit msg. Hope this works.

### CODE REVIEW

**Comment by Lysxia** [comment]
Ah I didn't expect it so fast :) In the meantime I also added a sentence about partial application in the README, what do you think of it?

**Comment by Lysxia** [comment]
Can you rebase this on the current `master`? (`git rebase master`)

**Comment by gspia** [comment]
can we talks shortly at irc?

**Comment by Lysxia** [comment]
Looks great, thanks!

**Comment by gspia** [comment]
Closes #18

**Pull request merged**
