### PR TITLE
Add prelude stuff

### PR DESCRIPTION
**Pull request by isovector**

### CODE REVIEW

**Comment by Lysxia** [comment]
Nice, thanks! My only nitpick is I would prefer to call it `MapList` instead of `ListMap`.

**Comment by isovector** [comment]
Cool! Is there a story for promoted typeclass polymorphism here? It'd be nice to write `Lookup` in terms of promoted fmap rather than its current implementation.

**Comment by isovector** [comment]
```haskell
type family Fmap (f :: a -> Exp b) (as :: m a) :: m b
type instance Fmap f '[] = '[]
type instance Fmap f (a ': as) = Eval (f a) ': Fmap f as

type instance Fmap f 'Nothing = 'Nothing
type instance Fmap f ('Just a) = 'Just (Eval (f a))
```

This works but I'm not sure it's in the spirit of fcf

**Comment by Lysxia** [comment]
That's neat. I'm in favour of using this to replace the monomorphic versions. (And I'd call it just `Map`.)

>  It'd be nice to write Lookup in terms of promoted fmap rather than its current implementation.

I didn't get that.

**Comment by isovector** [comment]
PTAL---added Map type instances for the usual prelude types except for `a -> Exp b` which I couldn't figure out how to do.

**Comment by Lysxia** [comment]
Awesome, thanks!

**Pull request merged**
